# JSON and XML - Lab

## Introduction

In this lab, you'll practice navigating JSON and XML data structures.

## Objectives
You will be able to:
* Effectively use the JSON module to load and parse JSON documents
* Read and access data stored in JSON and XML
* Compare  and contrast the JSON and XML as data interchange types

## XML

In [1]:
import xml.etree.ElementTree as ET

### Create an XML tree and retrieve the root tag.

In [2]:
#Your code here
tree = ET.parse('nyc_2001_campaign_finance.xml')
root = tree.getroot()

### How many direct descendents does the root tag have?

In [6]:
#Answer: 1
count = 0
for child in root:
    count += 1
print(count)

1

### How many different types of tags are there within the entire XML file?

In [8]:
# Your code here
tags = []
for element in root.iter():
    tags.append(element.tag)
print(len(set(tags)))

13

### Create a DataFrame listing the number of each type of tag. 
Sort the DataFrame in descending order by the tag count. The first entry should demonstrate there are 286 row tags in the XML file.   
(Your DataFrame will be a single column, so could also be thought of as a Series.)

In [9]:
import pandas as pd

In [11]:
#Your code here
tags = {}
for element in root.iter():
    tags[element.tag] = tags.get(element.tag, 0) + 1
df = pd.DataFrame.from_dict(tags, orient='index')
df.columns = ['count']
df = df.sort_values(by='count', ascending=False)
df

            count
row           286
candid        285
candname      285
canclass      285
election      284
officecd      284
primarypay    284
generalpay    284
runoffpay     284
totalpay      284
officedist    245
officeboro     21
response        1

## JSON

### Open the same dataset from json

In [12]:
#Your code here
import json
f = open('nyc_2001_campaign_finance.json')
data = json.load(f)

### What is the root data type of the json file?

In [13]:
### Your code here
print(type(data))

<class 'dict'>

### Navigate to the 'data' key of your loaded json object. What data type is this?

In [14]:
#Your code here
type(data['data'])

list

### Preview the first entry from the value returned by the 'data' key above.

In [15]:
#Your code here
data['data'][0]

[1,
 'E3E9CC9F-7443-43F6-94AF-B5A0F802DBA1',
 1,
 1315925633,
 '392904',
 1315925633,
 '392904',
 '{\n  "invalidCells" : {\n    "1519001" : "TOTALPAY",\n    "1518998" : "PRIMARYPAY",\n    "1519000" : "RUNOFFPAY",\n    "1518999" : "GENERALPAY",\n    "1518994" : "OFFICECD",\n    "1518996" : "OFFICEDIST",\n    "1518991" : "ELECTION"\n  }\n}',
 None,
 'CANDID',
 'CANDNAME',
 None,
 'OFFICEBORO',
 None,
 'CANCLASS',
 None,
 None,
 None,
 None]

### Preview the Entry under meta -> view -> columns (the keys of three successively nested dictionaries)

In [21]:
data['meta']['view']['columns']

[{'id': -1,
  'name': 'sid',
  'dataTypeName': 'meta_data',
  'fieldName': ':sid',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'id',
  'dataTypeName': 'meta_data',
  'fieldName': ':id',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'position',
  'dataTypeName': 'meta_data',
  'fieldName': ':position',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'created_at',
  'dataTypeName': 'meta_data',
  'fieldName': ':created_at',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'created_meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':created_meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'updated_at',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_at',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'updated_meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': 75768833,
  'name': 'ELECTION',
  'dataTypeName': 'number',
  'fieldName': 'election',
  'position': 2,
  'renderTypeName': 'number',
  'tableColumnId': 1518991,
  'width': 196,
  'cachedContents': {'non_null': 284,
   'average': '2001',
   'largest': '2001',
   'null': 1,
   'top': [{'item': '2001', 'count': 20}],
   'smallest': '2001',
   'sum': '568284'},
  'format': {'precisionStyle': 'standard',
   'noCommas': 'true',
   'align': 'right'}},
 {'id': 75768834,
  'name': 'CANDID',
  'dataTypeName': 'text',
  'fieldName': 'candid',
  'position': 3,
  'renderTypeName': 'text',
  'tableColumnId': 1518992,
  'width': 172,
  'cachedContents': {'non_null': 285,
   'largest': 'YA',
   'null': 0,
   'top': [{'item': '490', 'count': 20},
    {'item': '577', 'count': 19},
    {'item': 'GF', 'count': 18},
    {'item': '265', 'count': 17},
    {'item': '549', 'count': 16},
    {'item': '260', 'count': 15},
    {'item': 'DH', 'count': 14},
    {'item': '168', 'count': 13},
    {'item': '561', 'count': 12},
    {'item': '317', 'count': 11},
    {'item': '240', 'count': 10},
    {'item': 'B1', 'count': 9},
    {'item': '337', 'count': 8},
    {'item': '202', 'count': 7},
    {'item': 'DP', 'count': 6},
    {'item': '554', 'count': 5},
    {'item': '529', 'count': 4},
    {'item': '521', 'count': 3},
    {'item': 'CY', 'count': 2},
    {'item': '327', 'count': 1}],
   'smallest': '148'},
  'format': {}},
 {'id': 75768835,
  'name': 'CANDNAME',
  'dataTypeName': 'text',
  'fieldName': 'candname',
  'position': 4,
  'renderTypeName': 'text',
  'tableColumnId': 1518993,
  'width': 196,
  'cachedContents': {'non_null': 285,
   'largest': 'Zett, Lori M',
   'null': 0,
   'top': [{'item': 'Taitt, Samuel A', 'count': 20},
    {'item': 'Taliaferro, Phyllis', 'count': 19},
    {'item': 'Taveras, Germania', 'count': 18},
    {'item': 'Thakral, Jairam D', 'count': 17},
    {'item': 'Thomas, Carl W', 'count': 16},
    {'item': 'Thompson, Jr., William C', 'count': 15},
    {'item': 'Tiraco, Joseph E', 'count': 14},
    {'item': 'Toney, Vaughan', 'count': 13},
    {'item': 'Toppin, Roger N', 'count': 12},
    {'item': 'Torres, Mario A', 'count': 11},
    {'item': 'Vallone, Jr., Peter F', 'count': 10},
    {'item': 'Vallone, Peter F', 'count': 9},
    {'item': 'Van Bramer, James G', 'count': 8},
    {'item': 'Vann, Albert', 'count': 7},
    {'item': 'Vargas, Ruben Dario', 'count': 6},
    {'item': 'Vassos, Sandra', 'count': 5},
    {'item': 'Vernet, Jean D', 'count': 4},
    {'item': 'Viest, Nicholas D', 'count': 3},
    {'item': 'Villaverde, Sergio', 'count': 2},
    {'item': 'Vogel, Mark H', 'count': 1}],
   'smallest': 'Aboulafia, Sandy'},
  'format': {}},
 {'id': 75768836,
  'name': 'OFFICECD',
  'dataTypeName': 'number',
  'fieldName': 'officecd',
  'position': 5,
  'renderTypeName': 'number',
  'tableColumnId': 1518994,
  'width': 196,
  'cachedContents': {'non_null': 284,
   'average': '4.700704225352113',
   'largest': '5',
   'null': 1,
   'top': [{'item': '5', 'count': 20},
    {'item': '1', 'count': 19},
    {'item': '3', 'count': 18},
    {'item': '4', 'count': 17},
    {'item': '2', 'count': 16}],
   'smallest': '1',
   'sum': '1335'},
  'format': {}},
 {'id': 75768837,
  'name': 'OFFICEBORO',
  'dataTypeName': 'text',
  'fieldName': 'officeboro',
  'position': 6,
  'renderTypeName': 'text',
  'tableColumnId': 1518995,
  'width': 220,
  'cachedContents': {'non_null': 21,
   'largest': 'X',
   'null': 264,
   'top': [{'item': 'OFFICEBORO', 'count': 20},
    {'item': 'X', 'count': 19},
    {'item': 'M', 'count': 18},
    {'item': 'K', 'count': 17},
    {'item': 'Q', 'count': 16},
    {'item': 'S', 'count': 15}],
   'smallest': 'K'},
  'format': {}},
 {'id': 75768838,
  'name': 'OFFICEDIST',
  'dataTypeName': 'number',
  'fieldName': 'officedist',
  'position': 7,
  'renderTypeName': 'number',
  'tableColumnId': 1518996,
  'width': 220,
  'cachedContents': {'non_null': 245,
   'average': '26.33061224489796',
   'largest': '51',
   'null': 40,
   'top': [{'item': '7', 'count': 20},
    {'item': '32', 'count': 19},
    {'item': '37', 'count': 18},
    {'item': '28', 'count': 17},
    {'item': '19', 'count': 16},
    {'item': '39', 'count': 15},
    {'item': '35', 'count': 14},
    {'item': '42', 'count': 13},
    {'item': '31', 'count': 12},
    {'item': '6', 'count': 11},
    {'item': '47', 'count': 10},
    {'item': '20', 'count': 9},
    {'item': '1', 'count': 8},
    {'item': '27', 'count': 7},
    {'item': '26', 'count': 6},
    {'item': '10', 'count': 5},
    {'item': '34', 'count': 4},
    {'item': '45', 'count': 3},
    {'item': '40', 'count': 2},
    {'item': '12', 'count': 1}],
   'smallest': '1',
   'sum': '6451'},
  'format': {}},
 {'id': 75768839,
  'name': 'CANCLASS',
  'dataTypeName': 'text',
  'fieldName': 'canclass',
  'position': 8,
  'renderTypeName': 'text',
  'tableColumnId': 1518997,
  'width': 196,
  'cachedContents': {'non_null': 285,
   'largest': 'P',
   'null': 0,
   'top': [{'item': 'CANCLASS', 'count': 20}, {'item': 'P', 'count': 19}],
   'smallest': 'CANCLASS'},
  'format': {}},
 {'id': 75768840,
  'name': 'PRIMARYPAY',
  'dataTypeName': 'number',
  'fieldName': 'primarypay',
  'position': 9,
  'renderTypeName': 'number',
  'tableColumnId': 1518998,
  'width': 220,
  'cachedContents': {'non_null': 284,
   'average': '112243.9612676056',
   'largest': '2846148.00',
   'null': 1,
   'top': [{'item': '75350.00', 'count': 20},
    {'item': '0', 'count': 19},
    {'item': '91333.00', 'count': 18},
    {'item': '69780.00', 'count': 17},
    {'item': '22172.00', 'count': 16},
    {'item': '65356.00', 'count': 15},
    {'item': '11423.00', 'count': 14},
    {'item': '60152.00', 'count': 13},
    {'item': '75040.00', 'count': 12},
    {'item': '62436.00', 'count': 11},
    {'item': '42075.00', 'count': 10},
    {'item': '74920.00', 'count': 9},
    {'item': '38088.00', 'count': 8},
    {'item': '74850.00', 'count': 7},
    {'item': '89502.00', 'count': 6},
    {'item': '74350.00', 'count': 5},
    {'item': '58348.00', 'count': 4},
    {'item': '55100.00', 'count': 3},
    {'item': '508893.00', 'count': 2},
    {'item': '74750.00', 'count': 1}],
   'smallest': '0',
   'sum': '31877285.00'},
  'format': {}},
 {'id': 75768841,
  'name': 'GENERALPAY',
  'dataTypeName': 'number',
  'fieldName': 'generalpay',
  'position': 10,
  'renderTypeName': 'number',
  'tableColumnId': 1518999,
  'width': 220,
  'cachedContents': {'non_null': 284,
   'average': '28753.57394366197',
   'largest': '976545.00',
   'null': 1,
   'top': [{'item': '0', 'count': 20},
    {'item': '75350.00', 'count': 19},
    {'item': '201131.00', 'count': 18},
    {'item': '39760.00', 'count': 17},
    {'item': '57796.00', 'count': 16},
    {'item': '75200.00', 'count': 15},
    {'item': '68234.00', 'count': 14},
    {'item': '5732.00', 'count': 13},
    {'item': '58488.00', 'count': 12},
    {'item': '62184.00', 'count': 11},
    {'item': '44748.00', 'count': 10},
    {'item': '21946.00', 'count': 9},
    {'item': '70500.00', 'count': 8}],
   'smallest': '0',
   'sum': '8166015.00'},
  'format': {}},
 {'id': 75768842,
  'name': 'RUNOFFPAY',
  'dataTypeName': 'number',
  'fieldName': 'runoffpay',
  'position': 11,
  'renderTypeName': 'number',
  'tableColumnId': 1519000,
  'width': 208,
  'cachedContents': {'non_null': 284,
   'average': '7776.778169014085',
   'largest': '711537.00',
   'null': 1,
   'top': [{'item': '0', 'count': 20},
    {'item': '267331.00', 'count': 19},
    {'item': '574387.00', 'count': 18},
    {'item': '303270.00', 'count': 17},
    {'item': '711537.00', 'count': 16},
    {'item': '114407.00', 'count': 15},
    {'item': '237673.00', 'count': 14}],
   'smallest': '0',
   'sum': '2208605.00'},
  'format': {}},
 {'id': 75768843,
  'name': 'TOTALPAY',
  'dataTypeName': 'number',
  'fieldName': 'totalpay',
  'position': 12,
  'renderTypeName': 'number',
  'tableColumnId': 1519001,
  'width': 196,
  'cachedContents': {'non_null': 284,
   'average': '148774.3133802817',
   'largest': '4534230.00',
   'null': 1,
   'top': [{'item': '0', 'count': 20},
    {'item': '75350.00', 'count': 19},
    {'item': '150700.00', 'count': 18},
    {'item': '2458534.00', 'count': 17},
    {'item': '133146.00', 'count': 16},
    {'item': '75200.00', 'count': 15},
    {'item': '68234.00', 'count': 14},
    {'item': '70664.00', 'count': 13},
    {'item': '58488.00', 'count': 12},
    {'item': '50112.00', 'count': 11},
    {'item': '62184.00', 'count': 10},
    {'item': '44748.00', 'count': 9},
    {'item': '21946.00', 'count': 8},
    {'item': '41656.00', 'count': 7},
    {'item': '61260.00', 'count': 6},
    {'item': '145850.00', 'count': 5},
    {'item': '35808.00', 'count': 4},
    {'item': '12172.00', 'count': 3}],
   'smallest': '0',
   'sum': '42251905.00'},
  'format': {}}]

### Create a DataFrame from your json data
The previous two questions previewed one entry from the data object within the json file, as well as the column details associated with that data from the meta entry within the json file. Both should have 19 entries. Create a DataFrame of the data. Be sure to use the information from the meta entry to add appropriate column names to your DataFrame.

In [23]:
#Your code here
df = pd.DataFrame(data['data'])
cols = [i['name'] for i in data['meta']['view']['columns']]
df.columns = cols
df

,sid,id,position,created_at,created_meta,updated_at,updated_meta,meta,ELECTION,CANDID,CANDNAME,OFFICECD,OFFICEBORO,OFFICEDIST,CANCLASS,PRIMARYPAY,GENERALPAY,RUNOFFPAY,TOTALPAY
0,1,E3E9CC9F-7443-43F6-94AF-B5A0F802DBA1,1,1315925633,392904,1315925633,392904,"{\n ""invalidCells"" : {\n ""1519001"" : ""TOTA...",None,CANDID,CANDNAME,None,OFFICEBORO,None,CANCLASS,None,None,None,None
1,2,9D257416-581A-4C42-85CC-B6EAD9DED97F,2,1315925633,392904,1315925633,392904,{\n},2001,B4,"Aboulafia, Sandy",5,None,44,P,45410.00,0,0,45410.00
2,3,B80D7891-93CF-49E8-86E8-182B618E68F2,3,1315925633,392904,1315925633,392904,{\n},2001,445,"Adams, Jackie R",5,None,7,P,11073.00,0,0,11073.00
3,4,BB012003-78F5-406D-8A87-7FF8A425EE3F,4,1315925633,392904,1315925633,392904,{\n},2001,HF,"Addabbo, Joseph P",5,None,32,P,75350.00,73970.00,0,149320.00
4,5,945825F9-2F5D-47C2-A16B-75B93E61E1AD,5,1315925633,392904,1315925633,392904,{\n},2001,IR,"Alamo-Estrada, Agustin",5,None,14,P,25000.00,2400.00,0,27400.00
5,6,9546F502-39D6-4340-B37E-60682EB22274,6,1315925633,392904,1315925633,392904,{\n},2001,BR,"Allen, William A",5,None,9,P,62990.00,0,0,62990.00
6,7,4B6C74AD-17A0-4B7E-973A-2592D68A687D,7,1315925633,392904,1315925633,392904,{\n},2001,454,"Alleyne, Alithia",5,None,40,P,0,0,0,0
7,8,ABD22A5E-B8DA-446F-82BC-93AA11AF99DF,8,1315925633,392904,1315925633,392904,{\n},2001,375,"Alonso, Miguel",5,None,37,P,36121.00,680.00,0,36801.00
8,9,7CD36FB5-600F-44F5-A10C-CB3434B6805F,9,1315925633,392904,1315925633,392904,{\n},2001,241,"Andrews, Jr., Anthony D",5,None,28,P,68580.00,20156.00,0,88736.00
9,10,7C977007-BC4A-4A04-AE0E-B2946AFE7193,10,1315925633,392904,1315925633,392904,{\n},2001,504,"Ariola, JoAnn",5,None,32,P,0,69816.00,0,69816.00
10,11,09E1FEC7-1CA8-4C6B-8EA9-48AFB59B4736,11,1315925633,392904,1315925633,392904,{\n},2001,51,"Avella, Tony",5,None,19,P,75350.00,75170.00,0,150520.00
11,12,B2246B0E-2B34-411E-8205-8A413D6FC36B,12,1315925633,392904,1315925633,392904,{\n},2001,279,"Bader, Paul",5,None,39,P,75350.00,0,0,75350.00
12,13,2BA2F8A3-72FD-4108-9162-5654AE72095B,13,1315925633,392904,1315925633,392904,{\n},2001,81,"Badillo, Herman",1,None,None,P,356723.00,0,0,356723.00
13,14,A1886DC9-C832-43A0-8865-F1C72152CB0F,14,1315925633,392904,1315925633,392904,{\n},2001,591,"Baez, Maria",5,None,14,P,75350.00,14912.00,0,90262.00
14,15,F85C0201-7BC9-40A8-8AA1-D18E1E9DE1E7,15,1315925633,392904,1315925633,392904,{\n},2001,KH,"Baldwin-Ferguson, Imogene",5,None,35,P,0,0,0,0
15,16,97494A75-34A2-428F-9D9E-019E8CF7C337,16,1315925633,392904,1315925633,392904,{\n},2001,258,"Banks, Steven R",5,None,39,P,75350.00,0,0,75350.00
16,17,36BA4807-FA7C-4610-8EEB-63ADAB58EDC6,17,1315925633,392904,1315925633,392904,{\n},2001,DD,"Barron, Charles",5,None,42,P,75350.00,17148.00,0,92498.00
17,18,675CBD1F-CEE4-4848-A70E-E80DECE4E42B,18,1315925633,392904,1315925633,392904,{\n},2001,256,"Bastone, Terry A",5,None,11,P,47820.00,0,0,47820.00
18,19,19471488-6B68-4002-8333-9B1B69CBE326,19,1315925633,392904,1315925633,392904,{\n},2001,25,"Benjamin, Michael A",5,None,16,P,75280.00,32946.00,0,108226.00
19,20,3F81CC8B-6A61-43D0-AA7C-082DCD16AFE0,20,1315925633,392904,1315925633,392904,{\n},2001,HL,"Berman, Herbert E",3,None,None,P,1487732.00,89128.00,0,1576860.00
20,21,8234EA21-25DF-4450-9FD9-DFB37BCBB756,21,1315925633,392904,1315925633,392904,{\n},2001,560,"Bernace, Victor A",5,None,7,P,19520.00,0,0,19520.00
21,22,49D9E145-460C-4DA6-8BF4-5FD710369A70,22,1315925633,392904,1315925633,392904,{\n},2001,321,"Bilal, Charles A",5,None,28,P,0,0,0,0
22,23,F3BEDBD9-2ED9-4288-8927-1E94C99C6DF0,23,1315925633,392904,1315925633,392904,{\n},2001,330,"Blake, James",5,None,31,P,51676.00,0,0,51676.00
23,24,D5BF19D9-6A44-49E7-A09B-C1003ECAFDD2,24,1315925633,392904,1315925633,392904,{\n},2001,508,"Bloodsaw, Daryl G",5,None,7,P,37312.00,0,0,37312.00
24,25,394A5985-BC4B-4DA8-854A-D3F5732A377D,25,1315925633,392904,1315925633,392904,{\n},2001,550,"Bouchard, Michelle",5,None,3,P,0,65704.00,0,65704.00
25,26,2D3AEA15-20FE-4616-9478-488620DB9650,26,1315925633,392904,1315925633,392904,{\n},2001,399,"Brewer, Gale A",5,None,6,P,75350.00,75350.00,0,150700.00
26,27,23195BCD-91D4-4CC2-8710-E6CC670A15FA,27,1315925633,392904,1315925633,392904,{\n},2001,539,"Brook Krasny, Alec",5,None,47,P,66304.00,0,0,66304.00
27,28,5C6F0B3D-8D2B-4690-AFDC-0F4AED8189B2,28,1315925633,392904,1315925633,392904,{\n},2001,543,"Brooks, Curtis",5,None,12,P,0,0,0,0
28,29,9F78DA91-3585-4549-93D7-BC928A2ED528,29,1315925633,392904,1315925633,392904,{\n},2001,EC,"Brown, Everly D",5,None,31,P,0,0,0,0
29,30,E2ADADBB-AED6-4D63-A2B1-7190BA3CE4F0,30,1315925633,392904,1315925633,392904,{\n},2001,517,"Brown, Michael E",5,None,6,P,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,256,F363FC24-12D9-4BE1-86A9-0631D2D8BCDF,256,1315925633,392904,1315925633,392904,{\n},2001,317,"Torres, Mario A",5,None,7,P,6732.00,75350.00,0,82082.00
256,257,EDDBC514-5F1D-4CA9-AF1B-BDBC24F2706E,257,1315925633,392904,1315925633,392904,{\n},2001,240,"Vallone, Jr., Peter F",5,None,22,P,75150.00,39760.00,0,114910.00
257,258,9A78F2FA-08E9-4168-B25E-110BE9C94812,258,1315925633,392904,1315925633,392904,{\n},2001,B1,"Vallone, Peter F",1,None,None,P,2458534.00,0,0,2458534.00
258,259,714247BF-5BF4-457C-9357-C913A5AA2E6A,259,1315925633,392904,1315925633,392904,{\n},2001,337,"Van Bramer, James G",5,None,25,P,75350.00,57796.00,0,133146.00
259,260,9F32B08B-8A3A-4110-839E-F59713E069E1,260,1315925633,392904,1315925633,392904,{\n},2001,202,"Vann, Albert",5,None,36,P,0,75200.00,0,75200.00
260,261,3A9D36AD-2066-4E51-B6ED-A8FF5720519B,261,1315925633,392904,1315925633,392904,{\n},2001,DP,"Vargas, Ruben Dario",5,None,10,P,0,0,0,0
261,262,1F135761-81A0-435A-BF8E-CA7296A6114A,262,1315925633,392904,1315925633,392904,{\n},2001,554,"Vassos, Sandra",5,None,22,P,0,68234.00,0,68234.00
262,263,72B5E367-D882-4FCE-936D-0B9C8637B4B2,263,1315925633,392904,1315925633,392904,{\n},2001,529,"Vernet, Jean D",5,None,40,P,64932.00,5732.00,0,70664.00
263,264,EA4E25C9-612B-4F3D-89D7-8F6B26D3975E,264,1315925633,392904,1315925633,392904,{\n},2001,521,"Viest, Nicholas D",5,None,4,P,0,58488.00,0,58488.00
264,265,F91B084B-FAED-4A1D-90E8-52A340FB8A2F,265,1315925633,392904,1315925633,392904,{\n},2001,CY,"Villaverde, Sergio",5,None,14,P,0,0,0,0
265,266,B76D3522-4856-4EAD-8A6F-79E65B4128EA,266,1315925633,392904,1315925633,392904,{\n},2001,327,"Vogel, Mark H",5,None,11,P,50112.00,0,0,50112.00
266,267,F79134DD-5DE6-4C7B-8791-EA8BB7C4C28F,267,1315925633,392904,1315925633,392904,{\n},2001,382,"Wai, Sidique A",5,None,35,P,0,62184.00,0,62184.00
267,268,72494437-C32B-4626-B9E5-1DE9D03540CB,268,1315925633,392904,1315925633,392904,{\n},2001,513,"Walker, John P",4,S,None,P,0,44748.00,0,44748.00
268,269,0D83E4E0-474F-4290-A859-122332815D35,269,1315925633,392904,1315925633,392904,{\n},2001,510,"Walker, Willie",5,None,9,P,0,0,0,0
269,270,192D77FF-FE40-41BF-A146-BE87D9322E7A,270,1315925633,392904,1315925633,392904,{\n},2001,586,"Walsh, Ryan J",5,None,20,P,0,21946.00,0,21946.00
270,271,8B06A509-1404-4728-8B5A-5AC8DE74AAD4,271,1315925633,392904,1315925633,392904,{\n},2001,412,"Wasserman, Abraham E",5,None,35,P,41656.00,0,0,41656.00
271,272,3CC8E6EE-F9DF-416D-AB14-68540329579B,272,1315925633,392904,1315925633,392904,{\n},2001,475,"Wein, Joseph Funicell",5,None,50,P,61260.00,0,0,61260.00
272,273,F609DE63-3A75-42C9-A56B-1858719CDB7E,273,1315925633,392904,1315925633,392904,{\n},2001,551,"Weir, Elias J",5,None,46,P,0,0,0,0
273,274,65D2447B-BF25-4E0E-825E-5A767A9E12F9,274,1315925633,392904,1315925633,392904,{\n},2001,232,"Weprin, David I",5,None,23,P,75350.00,70500.00,0,145850.00
274,275,9197F20E-01CD-4598-B8B7-8084A5A4962A,275,1315925633,392904,1315925633,392904,{\n},2001,441,"Whitney, W Ruth",5,None,40,P,0,0,0,0
275,276,A7C41B53-E17D-4CE3-91E2-6742972D73C6,276,1315925633,392904,1315925633,392904,{\n},2001,568,"Willebrand, Julia A",1,None,None,P,0,0,0,0
276,277,1F360AA5-4F1C-41CE-9D81-F7E7A1295492,277,1315925633,392904,1315925633,392904,{\n},2001,583,"Williams, Charles",5,None,14,P,35808.00,0,0,35808.00
277,278,844B64C7-F3D5-4013-AAF5-D09A552B3D80,278,1315925633,392904,1315925633,392904,{\n},2001,528,"Williams, Peter M",5,None,35,P,75350.00,0,0,75350.00
278,279,20FD2993-F509-4BF4-ACD0-B28AFA5C0F3C,279,1315925633,392904,1315925633,392904,{\n},2001,489,"Williams-Pereira, Dorothy",4,Q,None,P,0,0,0,0
279,280,9D181CE6-2CA9-43EC-AAB9-E6E1593396F8,280,1315925633,392904,1315925633,392904,{\n},2001,588,"Wilson, Jay R",5,None,2,P,0,0,0,0
280,281,C50E6A4C-BDE9-4F12-97F4-95D467013540,281,1315925633,392904,1315925633,392904,{\n},2001,537,"Wilson, John H",5,None,13,P,0,0,0,0
281,282,04C6D19F-FF63-47B0-B26D-3B8F98B4C16B,282,1315925633,392904,1315925633,392904,{\n},2001,559,"Wooten, Donald T",5,None,42,P,0,0,0,0
282,283,A451E0E9-D382-4A97-AAD8-D7D382055F8D,283,1315925633,392904,1315925633,392904,{\n},2001,280,"Yassky, David",5,None,33,P,75350.00,75350.00,0,150700.00
283,284,E84BCD0C-D6F4-450F-B55B-3199A265C781,284,1315925633,392904,1315925633,392904,{\n},2001,274,"Zapiti, Mike",5,None,22,P,12172.00,0,0,12172.00
284,285,5BBC9676-2119-4FB5-9DAB-DE3F71B7681A,285,1315925633,392904,1315925633,392904,{\n},2001,442,"Zett, Lori M",5,None,24,P,0,0,0,0

### What's wrong with the first row of the DataFrame?

In [24]:
#Your code here
df.meta.iloc[0] #some of the column names were input as data

'{\n  "invalidCells" : {\n    "1519001" : "TOTALPAY",\n    "1518998" : "PRIMARYPAY",\n    "1519000" : "RUNOFFPAY",\n    "1518999" : "GENERALPAY",\n    "1518994" : "OFFICECD",\n    "1518996" : "OFFICEDIST",\n    "1518991" : "ELECTION"\n  }\n}'

#Your answer here

## Summary

Congratulations! You've started exploring some more complicated data structures used for the web and got to practice data munging and exploring!